#/*
# * Copyright 2008-2020 Anael MOBILIA
# *
# * This file is part of image-heberg.fr.
# *
# * image-heberg.fr is free software: you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation, either version 3 of the License, or
# * (at your option) any later version.
# *
# * image-heberg.fr is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with image-heberg.fr. If not, see <http://www.gnu.org/licenses/>
# */
# Language
language: php

# Autres prérequis
services:
  - mysql

# Créer la BDD avant de commencer
before_script:
  # Version de mysql
  - mysql -V
  # Création de la BDD
  - mysql -e "CREATE DATABASE imageheberg;"
  # Injection des tables de base
  - mysql imageheberg < database.sql
  # Copie du fichier de configuration
  - sh -c "mv __tests/config/config.php config/"
  # Insertion d'un jeu de données de test
  - mysql imageheberg < __tests/data.sql

jobs:
  include:
    - php: 5.6
      script:
        - wget https://phar.phpunit.de/phpunit-5.phar
        - chmod +x phpunit-5.phar
        - php phpunit-5.phar --version
        - php phpunit-5.phar --colors --debug __tests/

    - php: 7.0
      script:
        - wget https://phar.phpunit.de/phpunit-6.phar
        - chmod +x phpunit-6.phar
        - php phpunit-6.phar --version
        - php phpunit-6.phar --colors --debug __tests/

    - php: 7.1
      script:
        - wget https://phar.phpunit.de/phpunit-7.phar
        - chmod +x phpunit-7.phar
        - php phpunit-7.phar --version
        - php phpunit-7.phar --colors --debug __tests/

    - php: 7.2
      script:
        - wget https://phar.phpunit.de/phpunit-8.phar
        - chmod +x phpunit-8.phar
        - php phpunit-8.phar --version
        - php phpunit-8.phar --colors --debug __tests/

    - php: 7.3
      script:
        - wget https://phar.phpunit.de/phpunit-9.phar
        - chmod +x phpunit-9.phar
        - php phpunit-9.phar --version
        - php phpunit-9.phar --colors --debug __tests/

    - php: 7.4
      script:
        - wget https://phar.phpunit.de/phpunit-9.phar
        - chmod +x phpunit-9.phar
        - php phpunit-9.phar --version
        - php phpunit-9.phar --colors --debug __tests/
    
    - php: 7.4.5
      script:
        - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
        - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
        - chmod +x phpcs.phar
        - chmod +x phpcbf.phar
        - php phpcs.phar -h
        - php phpcbf.phar -h
        - php phpcs.phar --ignore=*/__tests/* --standard=PSR12 ./ -p

    - php: nightly
      script:
        - wget https://phar.phpunit.de/phpunit-9.phar
        - chmod +x phpunit-9.phar
        - php phpunit-9.phar --version
        - php phpunit-9.phar --colors --debug __tests/

  allow_failures:
    - php: nightly
    - php: 7.4.5
