name: Tests de l'application
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:        
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configuration PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpunit

    - name: Lancement de MySQL
      run: sudo /etc/init.d/mysql start

    - name: Mise en place de l'environnement
      run: |
        mysql -V
        mysql -u root -e "CREATE DATABASE imageheberg;"
        mysql -u root imageheberg < database.sql
        sh -c "mv __tests/config/config.php config/"
        mysql -u root imageheberg < __tests/data.sql

    - name : Test de l'application
      run: |
        phpunit --version
        phpunit --colors --debug __tests/
