name: PHPUnit - Tests de l'application
on: [push, pull_request, workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-20.04
    strategy:
      matrix:        
        php-versions: ['7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configuration PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: imagick, pdo_mysql
        tools: phpunit

    - name: Lancement de MySQL
      run: sudo /etc/init.d/mysql start

    - name: Informations sur l'environnement
      run: |
        php --version
        mysql -V
        phpunit --version
        php -r 'echo Imagick::getVersion()["versionString"];'
        php -r 'echo phpinfo();'
        
    - name: Mise en place de l'environnement
      run: |
        mysql -u root -proot -e "CREATE DATABASE imageheberg;"
        mysql -u root -proot imageheberg < database.sql
        sh -c "mv __tests/config/config.php config/"
        sh -c "mv __tests/ipv*.txt files/z_cache/"
        mysql -u root -proot imageheberg < __tests/data.sql

    - name : Test de l'application
      run: phpunit --colors --debug __tests/
